import {useState,useEffect} from 'react';
import {flushSync} from 'react-dom';
import {registerPortfolioTools} from './webmcp';
import {Aperture,LayoutDashboard,Layers3,Bell,SlidersHorizontal,ArrowUpRight,ReceiptText,ShieldCheck,Link2,History,RefreshCw,Search,ChevronRight,Plus,Command,Activity,CheckCircle2} from 'lucide-react';
import {loadState,post,money,number,Row,severityLabel} from './api';
import {Badge,Sparkline,Modal,Evidence,Empty} from './components';
import './styles.css';
import RuleEditor from './RuleEditor';
import ExitFlow from './ExitFlow';
import StockDetail from './StockDetail';
import {AlertsView,RulesView,OrdersView,AccountsView,AuditView} from './Views';

const NAV=[['overview','Overview',LayoutDashboard],['holdings','Holdings',Layers3],['alerts','Alert inbox',Bell],['rules','Exit rules',SlidersHorizontal],['orders','Orders',ReceiptText],['accounts','Connections',Link2],['audit','Audit trail',History]] as const;
export default function App(){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('overview'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Row|null>(null),[notice,setNotice]=useState(''),[ruleEdit,setRuleEdit]=useState<Row|null|undefined>(undefined),[alertReview,setAlertReview]=useState<Row|null>(null);
 useEffect(()=>registerPortfolioTools((state,alert)=>flushSync(()=>{setData(state);setSelected(null);setRuleEdit(undefined);setAlertReview(alert)})),[]);
 async function refresh(){try{setData(await loadState());setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{refresh();const id=setInterval(refresh,60000);return()=>clearInterval(id)},[]);
 async function scan(){setBusy(true);try{await post('scan');await refresh();setNotice('Scan complete. All active rules evaluated.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(notice){const id=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(id)}},[notice]);
 if(!data)return <div className="loading"><Aperture size={38}/><h1>Drishti</h1><p>{error||'Loading your portfolio…'}</p>{error&&<button onClick={refresh}>Try again</button>}</div>;
 const snapshotDate=new Date(data.asof+'T00:00:00+05:30').toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',year:'numeric'});
 const alerts=data.alerts.filter((a:Row)=>a.status==='active'),positions=data.positions.filter((p:Row)=>`${p.name} ${p.symbol} ${p.isin}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="app"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setView('overview')}}><span className="brand-mark"><Aperture size={25}/></span>drishti<span className="brand-period">.</span></a><div className="workspace"><span className="workspace-icon">P</span><div><strong>Personal portfolio</strong><small>INDIAN EQUITIES</small></div></div><nav>{NAV.map(([id,label,Icon])=><button className={view===id?'nav-item active':'nav-item'} key={id} aria-label={label} onClick={()=>{setView(id);setQuery('')}}><Icon size={19}/><span>{label}</span>{id==='alerts'&&<b>{alerts.length}</b>}</button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={21}/><strong>You stay in control</strong><p>Every exit needs your confirmation.</p><div className="mode"><span/> Simulation mode</div></div><div className="profile"><span>PI</span><div><strong>Personal investor</strong><small>Local workspace</small></div></div></aside>
 <div className="main"><header className="topbar"><span>Portfolio workspace <ChevronRight size={14}/> <strong>{NAV.find(n=>n[0]===view)?.[1]}</strong></span><div className="row"><span className="demo-label">DEMO DATA</span><span className="top-date">{snapshotDate} · EOD</span><button className="icon-button" onClick={()=>setView('alerts')} aria-label="Open alert inbox"><Bell size={19}/></button></div></header><main><div className="page-heading"><div><div className="eyebrow">YOUR INVESTMENTS, IN FOCUS</div><h1>{view==='overview'?'Portfolio overview':NAV.find(n=>n[0]===view)?.[1]}</h1><p>{view==='overview'?'A clear view across your accounts. Know what needs your attention.':({holdings:'All your accounts, consolidated by security.',alerts:'Understand what changed. Decide what to do next.',rules:'Your investment discipline, expressed as clear conditions.',orders:'Every confirmed exit, across every account.',accounts:'Your brokers and demat accounts, in one place.',audit:'A permanent record of rules, evidence and decisions.'} as Record<string,string>)[view]}</p></div><button className="button primary" onClick={scan} disabled={busy}><RefreshCw size={16} className={busy?'spin':''}/>{busy?'Scanning…':'Run scan'}</button></div>{data.positions.some((p:Row)=>p.valuationStale)&&<div className="warning-note">Some valuations use an older close or are unavailable. Exits for affected positions are blocked.</div>}{error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {(view==='overview'||view==='holdings')&&<><div className="stats"><div className="stat"><span>Equity value <Layers3 size={16}/></span><strong>{money(data.summary.equity)}</strong><small>{data.positions.length} stocks across {data.accounts.length} accounts</small></div><div className="stat"><span>Unrealised P&L <ArrowUpRight size={17}/></span><strong className={data.summary.pnl>=0?'positive':'negative'}>{data.summary.pnl>=0?'+':''}{money(data.summary.pnl)}</strong><small><b className="positive">{number(data.summary.pnlPct)}%</b> on invested value</small></div><div className="stat"><span>Active alerts <Bell size={16}/></span><strong>{alerts.length}<em>{data.summary.actionPositions} stocks to review</em></strong><small>Technical, fundamental & portfolio</small></div><div className="stat"><span>Available cash <ReceiptText size={16}/></span><strong>{money(data.summary.cash)}</strong><small>{number(data.risk.cash_pct,1)}% of total portfolio value</small></div></div>
 {view==='overview'&&<div className="insight-grid"><section className="panel health-panel"><div className="panel-title"><h2>Portfolio health</h2><span className="small muted">By equity value</span></div><div className="health-bar">{['Healthy','Watch','Warning','Action required','Data gap','Unmonitored'].filter(s=>['Healthy','Watch','Warning','Action required'].includes(s)||data.positions.some((p:Row)=>p.status===s)).map((s,i)=>{const weight=data.positions.filter((p:Row)=>p.status===s).reduce((sum:number,p:Row)=>sum+p.weight,0);return weight>0?<div key={s} style={{width:`${weight}%`,background:['#318d79','#c6a859','#df946c','#e6b1a2','#b8ad87','#aab3b8'][i]}} title={`${s}: ${number(weight)}%`}/>:null})}</div><div className="health-legend">{['Healthy','Watch','Warning','Action required','Data gap','Unmonitored'].filter(s=>['Healthy','Watch','Warning','Action required'].includes(s)||data.positions.some((p:Row)=>p.status===s)).map((s,i)=><div key={s}><span className={`dot d${i}`}/><span>{s}</span><strong>{data.positions.filter((p:Row)=>p.status===s).length}</strong></div>)}</div><div className="health-footer"><ShieldCheck size={16}/>{data.rules.filter((r:Row)=>r.enabled).length} rules monitoring your portfolio <span>Review-based exits</span></div></section><section className="attention"><div className="row spread"><span className="eyebrow">NEEDS YOUR ATTENTION</span><span className="attention-icon"><Activity size={18}/></span></div><h2>{data.summary.actionPositions?`${data.summary.actionPositions} holdings need a closer look`:'No holdings need an exit review'}</h2><p>Review the evidence behind a breach before deciding your next move.</p><button onClick={()=>setView('alerts')}>Review active alerts <ChevronRight size={17}/></button></section></div>}
 <div className="portfolio-grid"><section className="panel holdings-panel"><div className="panel-title"><h2>Your holdings <span className="count">{data.positions.length}</span></h2><label className="search"><Search size={16}/><input aria-label="Search holdings" placeholder="Search holdings" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="table-scroll"><table><thead><tr><th>COMPANY</th><th className="numeric">VALUE / WEIGHT</th><th className="numeric">P&L</th><th>60 SESSIONS</th><th>STATUS</th><th/></tr></thead><tbody>{positions.map((p:Row)=><tr key={p.isin} onClick={()=>setSelected(p)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')setSelected(p)}} aria-label={`View ${p.symbol}`}><td><div className="company"><div className={`ticker-icon ${p.symbol.toLowerCase()}`}>{p.symbol.slice(0,2)}</div><div><strong>{p.symbol}</strong><small>{p.accounts.length} account{p.accounts.length>1?'s':''} · {number(p.quantity,0)} shares</small></div></div></td><td className="numeric"><strong>{money(p.value)}</strong><small>{number(p.weight,1)}% of equity</small></td><td className="numeric"><strong className={p.pnl>=0?'positive':'negative'}>{p.pnl>=0?'+':''}{money(p.pnl)}</strong><small>{number(p.pnlPct)}%</small></td><td><Sparkline values={p.sparkline} color={p.sparkline[59]>=p.sparkline[0]?'#39837a':'#bc745f'}/></td><td><Badge value={p.severity} label={p.status}/></td><td><ChevronRight size={16} className="muted"/></td></tr>)}</tbody></table>{!positions.length&&<Empty title="No matching holdings" body="Try a company name, symbol, or ISIN."/>}</div><div className="table-footer"><span>Consolidated by ISIN</span><span>Prices & financials are fictional fixtures</span></div></section><aside className="right-column"><section className="panel"><div className="panel-title"><h2>Allocation</h2><span className="small muted">SECTORS</span></div><div className="sectors">{data.sectors.map((s:Row,i:number)=><div className="sector" key={s.name}><div className="row spread"><span>{s.name}</span><strong>{number(s.weight,1)}%</strong></div><div className="bar-track"><div style={{width:`${s.weight}%`,background:['#244f4c','#55867a','#9bb896','#c2caa2','#b3bac5','#d6dce0'][i]}}/></div></div>)}</div></section><section className="panel connected"><div className="panel-title"><h2>Connected accounts</h2></div>{data.accounts.map((a:Row)=><div className="connection" key={a.id}><span className={`account-logo ${a.id}`}>{a.name[0]}</span><div><strong>{a.name}</strong><small>{a.account}</small></div><CheckCircle2 size={16}/></div>)}<button className="text-button" onClick={()=>setView('accounts')}>Manage connections <ChevronRight size={15}/></button></section></aside></div></>}
 {view==='alerts'&&<AlertsView data={data} onAlert={setAlertReview}/>}
 {view==='rules'&&<RulesView data={data} onEdit={r=>setRuleEdit(r||null)} onChanged={refresh}/>}
 {view==='orders'&&<OrdersView data={data}/>}
 {view==='accounts'&&<AccountsView data={data}/>}
 {view==='audit'&&<AuditView data={data}/>}
 <footer className="page-footer"><span><ShieldCheck size={14}/> Simulation only · No live orders</span><span>Snapshot: {snapshotDate} · All amounts in INR</span></footer></main></div>
 {selected&&<StockDetail position={data.positions.find((p:Row)=>p.isin===selected.isin)||selected} data={data} onClose={()=>setSelected(null)} onSaved={refresh} onAlert={a=>{setSelected(null);setAlertReview(a)}} onRule={r=>{setSelected(null);setRuleEdit(r)}}/>}
 {ruleEdit!==undefined&&<RuleEditor data={data} rule={ruleEdit||undefined} onClose={()=>setRuleEdit(undefined)} onSaved={()=>{refresh();setNotice('Rule saved and portfolio re-evaluated.')}}/>}
 {alertReview&&<ExitFlow alert={alertReview} data={data} onClose={()=>setAlertReview(null)} onChanged={refresh}/>}
 {notice&&<div className="toast" role="status"><CheckCircle2 size={18}/>{notice}</div>}</div>
}
