import {useEffect,useRef,useId} from 'react';
import {X,Check,AlertTriangle} from 'lucide-react';
import {number,severityLabel,Row} from './api';
export function Badge({value,label}:{value:string,label?:string}){return <span className={`badge ${value}`}>{label||severityLabel[value]||value}</span>}
export function Sparkline({values,color='#39837a',height=32}:{values:number[],color?:string,height?:number}){const min=Math.min(...values),max=Math.max(...values); const points=values.map((v,i)=>`${i*120/(values.length-1)},${height-3-(v-min)/(max-min||1)*(height-6)}`).join(' '); return <svg className="sparkline" viewBox={`0 0 120 ${height}`} role="img" aria-label="Price trend over the last 60 sessions"><polyline points={points} stroke={color} strokeWidth="1.8" fill="none" strokeLinejoin="round"/></svg>}
export function Modal({title,children,onClose,wide=false}:{title:string,children:React.ReactNode,onClose:()=>void,wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null); const titleId=useId();
 useEffect(()=>{const el=ref.current;el?.showModal();return ()=>el?.close()},[]);
 useEffect(()=>{ref.current?.scrollTo(0,0)},[title]);
 return <dialog ref={ref} aria-labelledby={titleId} className={`modal ${wide?'wide':''}`} onCancel={onClose}><header className="modal-head"><h2 id={titleId}>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={21}/></button></header><div className="modal-body">{children}</div></dialog>
}
export function Evidence({node}:{node:Row}){if(node.children)return <div className="evidence-group"><div className="eyebrow">{node.mode==='all'?'ALL conditions · AND':'ANY condition · OR'} <span className={node.matched?'negative':'muted'}>{node.matched===null?'• Data unavailable':node.matched?'• Breached':'• Clear'}</span></div>{node.children.map((c:Row,i:number)=><Evidence key={i} node={c}/>)}</div>;
return <div className="evidence"><div className="row spread"><strong>{node.label}</strong>{node.matched===null?<Badge value="watch" label="Data gap"/>:node.matched?<AlertTriangle size={16} className="negative"/>:<Check size={16} className="positive"/>}</div><p className="muted small">{node.operator} {(node.rhsMetric?.startsWith('dma')?node.rhsMetric.slice(3)+' DMA':node.rhsMetric==='wma40'?'40-week MA':node.rhsMetric)||number(node.observations[0]?.threshold)} · {node.periods} consecutive {node.category==='fundamental'?'quarter(s)':node.metric.includes('week')||node.metric==='wma40'?'week(s)':node.category==='technical'?'session(s)':'snapshot'}</p><div className="evidence-rows">{node.observations.map((o:Row,i:number)=><div key={i}><span>{o.date}</span><strong>{number(o.value)} {node.unit}</strong><span>{node.operator} {number(o.threshold)} {node.unit}</span><span>{o.matched===null?'Unavailable':o.matched?'Breached':'Clear'}</span>{o.reason&&<small className="reason">{o.reason}</small>}{o.previous&&<small className="reason">Prior: {number(o.previous.value)} vs {number(o.previous.threshold)}</small>}</div>)}</div></div>}
export function Empty({title,body}:{title:string,body:string}){return <div className="empty"><Check size={28}/><h3>{title}</h3><p>{body}</p></div>}
