import {useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {Row,post,severityLabel} from './api';
import {Modal} from './components';
const defaultLeaf=(portfolio=false):Row=>({metric:portfolio?'max_stock_weight':'close',op:portfolio?'gt':'lt',...(portfolio?{value:20}:{rhsMetric:'dma200'}),periods:1});
const OPS:Record<string,string>={lt:'Less than',lte:'At most',gt:'Greater than',gte:'At least',eq:'Equals',crosses_below:'Crosses below',crosses_above:'Crosses above'};
export function ConditionEditor({node,onChange,metrics,depth=0,portfolio=false}:{node:Row,onChange:(n:Row)=>void,metrics:Row[],depth?:number,portfolio?:boolean}){
 const mode=node.all?'all':node.any?'any':null;
 if(mode){const children=node[mode] as Row[];return <div className="condition-group"><div className="row spread"><select aria-label="Combine conditions" value={mode} onChange={e=>onChange({[e.target.value]:children})}><option value="all">ALL conditions (AND)</option><option value="any">ANY condition (OR)</option></select><span className="muted small">{children.length} conditions</span></div>{children.map((child,i)=><div className="condition-child" key={i}><ConditionEditor node={child} onChange={n=>onChange({[mode]:children.map((c,j)=>i===j?n:c)})} metrics={metrics} depth={depth+1} portfolio={portfolio}/>{children.length>1&&<button className="icon-button remove-condition" aria-label={`Remove condition ${i+1}`} onClick={()=>onChange({[mode]:children.filter((_,j)=>i!==j)})}><Trash2 size={15}/></button>}</div>)}<div className="row wrap"><button type="button" className="button" disabled={children.length>=10} onClick={()=>onChange({[mode]:[...children,defaultLeaf(portfolio)]})}><Plus size={14}/>Add condition</button>{depth<2&&<button type="button" className="button" disabled={children.length>=10} onClick={()=>onChange({[mode]:[...children,{any:[defaultLeaf(portfolio)]}]})}>Add nested group</button>}</div></div>}
 const metric=metrics.find(m=>m.key===node.metric)||metrics[0];const weekly=['weekly_close','wma40'].includes(node.metric);const compatible=metrics.filter(m=>m.category===metric.category&&m.unit===metric.unit&&(['weekly_close','wma40'].includes(m.key)===weekly));
 return <div className="condition-fields"><label>Metric<select aria-label="Condition metric" value={node.metric} onChange={e=>onChange({metric:e.target.value,op:'lt',value:0,periods:1})}>{metrics.map(m=><option value={m.key} key={m.key}>{m.label}</option>)}</select></label><label>Comparison<select aria-label="Condition comparison" value={node.op} onChange={e=>onChange({...node,op:e.target.value})}>{Object.entries(OPS).filter(([k])=>metric.category==='technical'||!k.startsWith('crosses')).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Compare against<select aria-label="Threshold type" value={node.rhsMetric?'metric':'value'} onChange={e=>{const n={...node};delete n.value;delete n.rhsMetric;onChange({...n,...(e.target.value==='metric'?{rhsMetric:compatible[0].key}:{value:0})})}}><option value="value">Number ({metric.unit})</option>{compatible.length>0&&<option value="metric">Another metric</option>}</select></label>{node.rhsMetric?<label>Reference metric<select aria-label="Reference metric" value={node.rhsMetric} onChange={e=>onChange({...node,rhsMetric:e.target.value})}>{compatible.map(m=><option value={m.key} key={m.key}>{m.label}</option>)}</select></label>:<label>Threshold · {metric.unit}<input aria-label="Threshold" type="number" step="any" value={node.value??0} onChange={e=>onChange({...node,value:e.target.value===''?'':Number(e.target.value)})}/></label>}<label>Consecutive {metric.category==='fundamental'?'quarters':weekly?'weeks':'periods'}<select aria-label="Consecutive periods" value={node.periods||1} disabled={['event','portfolio'].includes(metric.category)} onChange={e=>onChange({...node,periods:Number(e.target.value)})}>{Array.from({length:['event','portfolio'].includes(metric.category)?1:8},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label></div>
}
export default function RuleEditor({data,rule,onClose,onSaved}:{data:Row,rule?:Row,onClose:()=>void,onSaved:()=>void}){
 const [draft,setDraft]=useState<Row>(rule?structuredClone(rule):{name:'',scope:'stock',isin:'*',severity:'warning',enabled:true,condition:{all:[defaultLeaf()]}}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const metrics=data.metricsCatalog.filter((m:Row)=>(m.category==='portfolio')===(draft.scope==='portfolio'));
 const update=(patch:Row)=>setDraft({...draft,...patch});
 async function save(){setBusy(true);setError('');try{await post('rules',draft);onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Modal title={rule?'Edit exit rule':'Create an exit rule'} onClose={onClose} wide><div className="form-grid"><label>Rule name<input autoFocus placeholder="e.g. Two closes below 200 DMA" maxLength={120} value={draft.name} onChange={e=>update({name:e.target.value})}/></label><label>Severity<select value={draft.severity} onChange={e=>update({severity:e.target.value})}>{Object.entries(severityLabel).filter(([k])=>k!=='healthy').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Monitor<select value={draft.scope} onChange={e=>update({scope:e.target.value,isin:'*',condition:{all:[defaultLeaf(e.target.value==='portfolio')]}})}><option value="stock">Stock conditions</option><option value="portfolio">Portfolio risk</option></select></label>{draft.scope==='stock'&&<label>Apply to<select value={draft.isin} onChange={e=>update({isin:e.target.value})}><option value="*">All holdings</option>{data.positions.map((p:Row)=><option value={p.isin} key={p.isin}>{p.symbol}</option>)}</select></label>}</div><div className="rule-help"><strong>When these conditions are true, create an alert.</strong><p>Technical periods are completed sessions or weeks. Fundamental periods are published quarters. “Hard exit” sets urgency; every order still needs confirmation.</p></div><ConditionEditor node={draft.condition} onChange={condition=>update({condition})} metrics={metrics} portfolio={draft.scope==='portfolio'}/>{!draft.condition.all&&!draft.condition.any&&<button className="text-button" onClick={()=>update({condition:{all:[draft.condition,defaultLeaf(draft.scope==='portfolio')]}})}>Add another condition</button>}<label className="checkbox-row"><input type="checkbox" checked={draft.enabled} onChange={e=>update({enabled:e.target.checked})}/>Enable this rule</label>{error&&<div className="error" role="alert">{error}</div>}<div className="modal-actions"><button className="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy||!draft.name.trim()} onClick={save}>{busy?'Saving…':'Save rule'}</button></div></Modal>
}
