import {useState,useEffect} from 'react';
import {Save,ChevronRight} from 'lucide-react';
import {Row,post,money,number} from './api';
import {Modal,Badge,Evidence,Empty} from './components';
function PriceChart({security}:{security:Row}){
 const bars=security.bars,visible=bars.slice(-90);const line=visible.map((b:Row,i:number)=>({date:b.date,price:b.close,ma:bars.slice(bars.length-90+i-199,bars.length-90+i+1).reduce((s:number,r:Row)=>s+r.close,0)/200}));
 const lo=Math.min(...line.flatMap((x:Row)=>[x.price,x.ma]))*.985,hi=Math.max(...line.flatMap((x:Row)=>[x.price,x.ma]))*1.015;
 const path=(key:string)=>line.map((v:Row,i:number)=>`${55+i*700/89},${195-(v[key]-lo)/(hi-lo)*160}`).join(' ');
 return <div className="price-chart"><svg viewBox="0 0 780 225" role="img" aria-label="Last 90 sessions of synthetic close prices and 200-day moving average">{[0,1,2,3].map(i=><g key={i}><line x1="55" x2="755" y1={35+i*53.3} y2={35+i*53.3} stroke="#e6eeea"/><text x="0" y={39+i*53.3} fill="#81928b" fontSize="10">{number(hi-(hi-lo)*i/3,0)}</text></g>)}<polyline points={path('ma')} fill="none" stroke="#c49f58" strokeWidth="2" strokeDasharray="6 4"/><polyline points={path('price')} fill="none" stroke="#3d806e" strokeWidth="2.5"/>{[0,44,89].map(i=><text key={i} x={55+i*700/89} y="221" fill="#81928b" fontSize="10" textAnchor={i===89?'end':'start'}>{visible[i].date}</text>)}</svg><div className="row small muted"><span className="chart-key price"/> Daily close <span className="chart-key ma"/> 200 DMA <span className="chart-disclaimer">Synthetic data</span></div></div>
}
export default function StockDetail({position,data,onClose,onSaved,onAlert,onRule}:{position:Row,data:Row,onClose:()=>void,onSaved:()=>void,onAlert:(a:Row)=>void,onRule:(r:Row)=>void}){
 const [tab,setTab]=useState('overview'),[security,setSecurity]=useState<Row|null>(null),[thesis,setThesis]=useState(data.theses[position.isin]||''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{fetch(`/api/security/${position.isin}`).then(async r=>{const s=await r.json();if(!r.ok)throw Error(s.error);setSecurity(s)}).catch(e=>setError(e.message))},[position.isin]);
 const alerts=data.alerts.filter((a:Row)=>a.target===position.isin),evaluations=data.evaluations.filter((e:Row)=>e.target===position.isin),rules=data.rules.filter((r:Row)=>r.scope==='stock'&&['*',position.isin].includes(r.isin));
 async function save(){setBusy(true);try{await post('thesis',{isin:position.isin,body:thesis});onSaved();setMessage('Thesis saved to your audit trail.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Modal title={`${position.symbol} · Position intelligence`} onClose={onClose} wide><div className="row spread"><div><p>{position.name}</p><p className="small muted">{position.isin} · {position.sector}</p></div><Badge value={position.severity} label={position.status}/></div><div className="detail-stats"><div><span>Holding value</span><strong>{money(position.value)}</strong></div><div><span>Shares / sellable</span><strong>{number(position.quantity,0)} / {number(position.available,0)}</strong></div><div><span>Average cost</span><strong>{money(position.avgCost)}</strong></div><div><span>Unrealised P&L</span><strong className={position.pnl>=0?'positive':'negative'}>{money(position.pnl)}</strong></div></div><div className="tabs" role="tablist">{['overview','fundamentals','thesis','rules','history'].map(t=><button role="tab" aria-selected={tab===t} className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{error&&<div className="error">{error}</div>}
 {tab==='overview'&&<>{security?<PriceChart security={security}/>:<p className="padded muted">Loading history…</p>}<div className="metric-grid">{['close','dma20','dma50','dma100','dma200','weekly_close','wma40','drawdown_pct','volume_ratio'].map(k=><div key={k}><span>{data.metricsCatalog.find((m:Row)=>m.key===k)?.label}</span><strong>{number(position.metrics[k])} <small>{data.metricsCatalog.find((m:Row)=>m.key===k)?.unit}</small></strong></div>)}</div><h3 className="section-label">Account breakdown</h3><div className="table-scroll"><table className="detail-table"><thead><tr><th>ACCOUNT</th><th>HELD</th><th>PLEDGED</th><th>BLOCKED</th><th>UNSETTLED</th><th>SELLABLE</th></tr></thead><tbody>{position.accounts.map((a:Row)=><tr key={a.account_id}><td>{data.accounts.find((x:Row)=>x.id===a.account_id)?.name}</td><td>{number(a.quantity,0)}</td><td>{number(a.pledged,0)}</td><td>{number(a.blocked,0)}</td><td>{number(a.unsettled,0)}</td><td><strong>{number(a.available,0)}</strong></td></tr>)}</tbody></table></div><h3 className="section-label">Active alerts</h3>{alerts.filter((a:Row)=>a.status==='active').map((a:Row)=><button key={a.id} className="alert-row compact" onClick={()=>onAlert(a)}><div><strong>{a.title}</strong></div><Badge value={a.severity}/><ChevronRight size={17}/></button>)}{!position.breaches&&<Empty title="No active breaches" body="Your enabled rules are currently clear."/>}</>}
 {tab==='fundamentals'&&<><div className="info-note">Fictional, normalised data. Latest quarter: {security?.fundamentals[0].period}; published {security?.fundamentals[0].publishedAt}. Banking metrics that do not apply are left unavailable.</div><div className="metric-grid">{data.metricsCatalog.filter((m:Row)=>m.category==='fundamental').map((m:Row)=><div key={m.key}><span>{m.label}</span><strong>{number(position.metrics[m.key])} <small>{position.metrics[m.key]==null?'':m.unit}</small></strong></div>)}</div><h3 className="section-label">Corporate events · last 90 days</h3>{security?.events.length?security.events.map((e:Row,i:number)=><div className="event-item" key={i}><strong>{e.title}</strong><p>{e.date} · {e.source}</p></div>):<p className="padded muted">No events in the fictional snapshot.</p>}</>}
 {tab==='thesis'&&<div className="thesis-editor"><label>Your reason for holding<textarea rows={7} maxLength={5000} value={thesis} onChange={e=>{setThesis(e.target.value);setMessage('')}}/></label><p className="muted small">Write the growth, profitability and risk assumptions you want your rules to monitor.</p><div className="modal-actions"><span className="positive small">{message}</span><button className="button primary" disabled={busy} onClick={save}><Save size={15}/>{busy?'Saving…':'Save thesis'}</button></div></div>}
 {tab==='rules'&&<>{rules.map((r:Row)=>{const e=evaluations.find((e:Row)=>e.ruleId===r.id);return <details className="rule-result" key={r.id}><summary><span>{r.name}</span><Badge value={!r.enabled?'resolved':e?.matched===true?r.severity:e?.matched===null?'watch':'healthy'} label={!r.enabled?'Disabled':e?.matched===true?'Breached':e?.matched===null?'Data gap':'Clear'}/></summary>{e&&<Evidence node={e.evidence}/>}<button className="text-button" onClick={()=>onRule(r)}>Edit this rule</button></details>})}</>}
 {tab==='history'&&<>{alerts.length?alerts.map((a:Row)=><button className="alert-row" key={a.id} onClick={()=>onAlert(a)}><div><strong>{a.title}</strong><p>{a.status} · rule version {a.version}</p></div><Badge value={a.severity}/><ChevronRight size={16}/></button>):<Empty title="No trigger history" body="Alerts will appear here when a rule is breached."/>}</>}
 </Modal>
}
