import {useState} from 'react';
import {Plus,ChevronRight,ShieldCheck,Link2,CheckCircle2,Search,Download,SlidersHorizontal} from 'lucide-react';
import {Row,post,money,number,dateTime,severityLabel} from './api';
import {Badge,Empty,Evidence} from './components';

function describe(n:Row,metrics:Row[]):string{if(n.all||n.any){const mode=n.all?'all':'any';return '('+n[mode].map((c:Row)=>describe(c,metrics)).join(mode==='all'?' AND ':' OR ')+')'}const label=(k:string)=>metrics.find(m=>m.key===k)?.label||k;const ops:Row={lt:'<',lte:'≤',gt:'>',gte:'≥',eq:'=',crosses_below:'crosses below',crosses_above:'crosses above'};return `${label(n.metric)} ${ops[n.op]} ${n.rhsMetric?label(n.rhsMetric):number(n.value)}${n.periods>1?` for ${n.periods} periods`:''}`}
export function AlertsView({data,onAlert}:{data:Row,onAlert:(a:Row)=>void}){
 const [status,setStatus]=useState('active'),[severity,setSeverity]=useState('all'),[search,setSearch]=useState('');
 const rows=data.alerts.filter((a:Row)=>(status==='reviewed'?a.acknowledged:a.status===status)&&(severity==='all'||a.severity===severity)&&`${a.symbol} ${a.title}`.toLowerCase().includes(search.toLowerCase()));
 return <><div className="view-toolbar"><div className="tabs"><button className={status==='active'?'selected':''} onClick={()=>setStatus('active')}>Active <span>{data.alerts.filter((a:Row)=>a.status==='active').length}</span></button><button className={status==='reviewed'?'selected':''} onClick={()=>setStatus('reviewed')}>Reviewed</button><button className={status==='resolved'?'selected':''} onClick={()=>setStatus('resolved')}>Resolved</button></div><div className="row wrap"><label className="search"><Search size={16}/><input aria-label="Search alerts" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search alerts"/></label><select aria-label="Alert severity" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">All severities</option>{Object.entries(severityLabel).filter(([k])=>k!=='healthy').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div></div><div className="info-note"><ShieldCheck size={18}/>Alerts never sell shares automatically. Review the evidence, choose an exit amount, then confirm the order preview.</div><section className="panel">{rows.map((a:Row)=><button className="alert-row" key={a.id} onClick={()=>onAlert(a)}><div className={`alert-symbol ${a.target==='portfolio'?'portfolio-symbol':''}`}>{a.target==='portfolio'?<SlidersHorizontal size={19}/>:a.symbol.slice(0,2)}</div><div><div className="row wrap"><strong>{a.symbol}</strong>{a.acknowledged===1&&<span className="reviewed-label">Reviewed</span>}{a.matched===null&&<Badge value="watch" label="Data gap"/>}</div><p>{a.title}</p><small className="muted">Observed {a.asof} · Rule version {a.version} · {a.target==='portfolio'?'Portfolio risk':'Stock rule'}</small></div><Badge value={a.status==='resolved'?'resolved':a.severity} label={a.status==='resolved'?'Resolved':undefined}/><span className="review-link">Review</span><ChevronRight size={17}/></button>)}{!rows.length&&<Empty title="No alerts in this view" body="Adjust the filters or run a scan to evaluate your rules."/>}</section>{data.summary.unknowns>0&&<div className="warning-note">{data.summary.unknowns} rule evaluations have missing data. Open the stock’s Rules tab for details.</div>}</>
}
export function RulesView({data,onEdit,onChanged}:{data:Row,onEdit:(r?:Row)=>void,onChanged:()=>void}){
 const [scope,setScope]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState('');
 async function toggle(r:Row){setBusy(r.id);setError('');try{await post('rules',{...r,enabled:!r.enabled});onChanged()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 return <><div className="view-toolbar"><div className="tabs">{['all','stock','portfolio'].map(s=><button key={s} className={scope===s?'selected':''} onClick={()=>setScope(s)}>{s==='all'?'All rules':s==='stock'?'Stock rules':'Portfolio risk'}</button>)}</div><button className="button primary" onClick={()=>onEdit()}><Plus size={16}/>Create rule</button></div><div className="info-note">Rules are deterministic and versioned. A new version re-evaluates holdings and preserves prior alert evidence. Sample thresholds are editable examples.</div>{error&&<div className="error">{error}</div>}<div className="rules-list">{data.rules.filter((r:Row)=>scope==='all'||r.scope===scope).map((r:Row)=>{const evaluations=data.evaluations.filter((e:Row)=>e.ruleId===r.id),breaches=evaluations.filter((e:Row)=>e.matched===true),unknowns=evaluations.filter((e:Row)=>e.matched===null);return <article className={`panel rule-card ${!r.enabled?'disabled-rule':''}`} key={r.id}><div className="row spread"><div><div className="eyebrow">{r.scope==='portfolio'?'PORTFOLIO RISK':r.isin==='*'?'ALL HOLDINGS':data.positions.find((p:Row)=>p.isin===r.isin)?.symbol||r.isin} · VERSION {r.version}</div><h2>{r.name}</h2></div><label className="switch"><input aria-label={`Enable ${r.name}`} type="checkbox" checked={r.enabled} disabled={busy===r.id} onChange={()=>toggle(r)}/><span/></label></div><p className="rule-expression">{describe(r.condition,data.metricsCatalog)}</p><div className="row spread"><div className="row wrap"><Badge value={r.severity}/><span className="small muted">{r.enabled?`${breaches.length} breached · ${evaluations.length} evaluated${unknowns.length?` · ${unknowns.length} unavailable`:''}`:'Disabled'}</span></div><button className="button" onClick={()=>onEdit(r)}>Edit rule</button></div>{r.scope==='portfolio'&&evaluations[0]&&<details className="risk-evidence"><summary>Current portfolio evidence</summary><Evidence node={evaluations[0].evidence}/></details>}</article>})}</div></>
}
export function OrdersView({data}:{data:Row}){return <><div className="info-note"><ShieldCheck size={18}/>All orders here are simulated fills. Original quantities, allocations and trigger evidence are retained in the audit trail.</div>{data.executions.length?<section className="panel">{data.executions.map((e:Row)=><details className="order-entry" key={e.id}><summary><div><strong>{e.symbol}</strong><p>{number(e.quantity,0)} shares · {dateTime(e.createdAt)} IST</p></div><strong>{money(e.proceeds)}</strong><Badge value="healthy" label="Simulated fill"/></summary><div className="receipt-list">{e.orders.map((o:Row)=><div key={o.broker_order_id}><strong>{data.accounts.find((a:Row)=>a.id===o.accountId)?.name}</strong><span>{o.quantity} shares at {money(o.fill_price)}</span><small>{o.broker_order_id}</small></div>)}</div><p className="small muted">Execution ID: {e.id}</p></details>)}</section>:<section className="panel"><Empty title="No exits yet" body="Start from an active stock alert. Review its evidence, choose 25%, 50% or 100%, and preview your order."/></section>}</>}
export function AccountsView({data}:{data:Row}){return <><div className="info-note"><Link2 size={18}/>Three mock broker connections are ready. Holdings are grouped by ISIN, while each broker and demat account stays separate for execution.</div><div className="account-cards">{data.accounts.map((a:Row)=>{const lots=data.positions.flatMap((p:Row)=>p.accounts.filter((h:Row)=>h.account_id===a.id).map((h:Row)=>({...h,price:p.price})));return <section className="panel account-card" key={a.id}><div className="row"><span className={`account-logo ${a.id}`}>{a.name[0]}</span><div><h2>{a.name}</h2><span className="small muted">Trading account {a.account}</span></div></div><div className="connection-state"><CheckCircle2 size={16}/>Mock connected</div><strong className="account-value">{money(lots.reduce((n:number,h:Row)=>n+h.quantity*h.price,0))}</strong><p className="muted small">{lots.length} holdings · {number(lots.reduce((n:number,h:Row)=>n+h.quantity,0),0)} shares</p><dl><dt>Demat reference</dt><dd>{a.demat}</dd><dt>Data source</dt><dd>Local seed + simulated fills</dd><dt>Execution</dt><dd>Mock market orders only</dd></dl></section>})}</div><section className="panel integration-note"><h2>Ready for real adapters, when you are</h2><p>Broker holdings, market data and order submission have separate interfaces. Live authentication, settlement authorisation, order reconciliation and market-session checks must be implemented before connecting an actual broker.</p><p className="muted small">No credentials are requested or stored by this prototype.</p></section></>}
export function AuditView({data}:{data:Row}){
 const [query,setQuery]=useState('');const rows=data.audit.filter((a:Row)=>`${a.action} ${a.target}`.toLowerCase().includes(query.toLowerCase()));
 function download(){const blob=new Blob([JSON.stringify(data.audit,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='drishti-audit-recent.json';a.click();URL.revokeObjectURL(url)}
 return <><div className="view-toolbar"><label className="search"><Search size={16}/><input aria-label="Filter audit trail" placeholder="Filter events" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="button" onClick={download}><Download size={16}/>Export recent events</button></div><div className="info-note">Append-only local audit log. Showing up to 250 recent events; the database retains all events. Times are displayed in IST.</div><section className="panel audit-list">{rows.map((a:Row)=><details key={a.id}><summary><span className="audit-number">#{a.id}</span><div><strong>{a.action.replaceAll('_',' ')}</strong><small>{a.target}</small></div><span className="small muted">{dateTime(a.at)}</span></summary><pre>{JSON.stringify(a.details,null,2)}</pre></details>)}{!rows.length&&<Empty title="No matching events" body="Try a different event name or security ISIN."/>}</section></>
}
